services:
  - type: web
    name: puter-selfhosted
    runtime: node
    region: oregon
    plan: free
    branch: main
    buildCommand: npm install
    startCommand: sh start-render.sh
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4100
